version: '3'

services:
  db:
    container_name: 'curly_db'
    env_file:
      - ./.env
    image: 'postgres:14'
    restart: always
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
  ping:
    image: willfarrell/ping
    environment:
      HOSTNAME: "localhost"
      TIMEOUT: 300

    